# .gitlab-ci.yml

# The names and order of the pipeline stages
stages:
  - install-dependencies
  - commit
  - push

install:
  stage: install-dependencies
  script:
    - echo "install git"
    - apk update && apk upgrade && apk add git && apk add --no-cache openssh   
    - mkdir -p ~/.ssh/
    - cp ${id_rsa} ~/.ssh/id_rsa    
    - chmod  0600 ~/.ssh/id_rsa    
    - ssh-keyscan github.com >> ~/.ssh/known_hosts      
    - git config --global user.name "${REMOTE_USER}"
    - git config --global user.email "${REMOTE_EMAIL}"
    - echo  ${REMOTE_REPO}            
    - git remote set-url origin git@github.com:pepeantonioGarcia/proxmox-terraform-homelab.git
    - git push -u origin main