# .gitlab-ci.yml
# The names and order of the pipeline stages
stages:
  - install-dependencies
  # Terraform section
  - validate
  - plan
  - apply
  # Terraform section

install:  
  stage: install-dependencies
  script:
    - echo "install git"
    - apk update && apk upgrade && apk add git && apk add rsync && apk add --no-cache openssh 
    - mkdir -p ~/.ssh/
    - cp ${id_rsa} ~/.ssh/id_rsa    
    - chmod  0600 ~/.ssh/id_rsa    
    - ssh-keyscan github.com >> ~/.ssh/known_hosts      
    - git config --global user.name "${REMOTE_USER}"
    - git config --global user.email "${REMOTE_EMAIL}"
    - git clone ${REMOTE_REPO} ~/remote
    - export PWD=$(pwd)        
    - rsync -r --exclude='.git/' ${PWD}/ ~/remote --delete    
    - cd ~/remote
    - git checkout ${CI_COMMIT_REF_NAME}    
    - git add .
    - git commit -m "Sync gitlab to Github by Jose Garcia"    
    - git push

validate:
  stage: validate
  before_script:
    - apk add terraform --repository=http://dl-cdn.alpinelinux.org/alpine/v3.12/main
    - apk update && apk upgrade && apk add terraform    
    - cd terraform
    - rm -rf .terraform
    - terraform --version
    - terraform init
  script:    
    - terraform validate    
plan:
  stage: plan
  script:
    - terraform plan -out "planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile
apply:
  stage: apply
  script:
    - terraform apply -input=false "planfile"
  dependencies:
    - plan
  when: manual
